---
title: "Ejemplo"
author: "Enrique Bonilla, Kael Huerta"
date: "Julio 6, 2016"
output: 
  ioslides_presentation:
    toc: yes
header-includes: 
- \usepackage[spanish]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{amsmath,amsfonts,amsthm}
- \usepackage{graphicx}
 
runtime: shiny
---

# Introducci贸n

## Shiny Presentation

Otra opci贸n es usar la presentaci贸n con shiny. 

# Shiny

## Slide with Interactive Plot

```{r, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```


# Presentaci贸n

## Output prueba

```{r, eval=T}
print("Hello world")
```

$$\beta$$

## Output prueba 2

- Bullet 1
- Bullet 2
- Bullet 3

## Output prueba 3

```{r, eval=T, include=T, height=4, width=8}
plot(mtcars)
```


